// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: IPC.proto

#include "IPC.pb.h"
#include "IPC.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace IPC {

static const char* IPCSrv_method_names[] = {
  "/IPC.IPCSrv/call",
  "/IPC.IPCSrv/streamCall",
  "/IPC.IPCSrv/recordDownload",
};

std::unique_ptr< IPCSrv::Stub> IPCSrv::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< IPCSrv::Stub> stub(new IPCSrv::Stub(channel, options));
  return stub;
}

IPCSrv::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_call_(IPCSrv_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_streamCall_(IPCSrv_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_recordDownload_(IPCSrv_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::Status IPCSrv::Stub::call(::grpc::ClientContext* context, const ::IPC::IPCRequest& request, ::IPC::IPCReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::IPC::IPCRequest, ::IPC::IPCReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_call_, context, request, response);
}

void IPCSrv::Stub::async::call(::grpc::ClientContext* context, const ::IPC::IPCRequest* request, ::IPC::IPCReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::IPC::IPCRequest, ::IPC::IPCReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_call_, context, request, response, std::move(f));
}

void IPCSrv::Stub::async::call(::grpc::ClientContext* context, const ::IPC::IPCRequest* request, ::IPC::IPCReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_call_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::IPC::IPCReply>* IPCSrv::Stub::PrepareAsynccallRaw(::grpc::ClientContext* context, const ::IPC::IPCRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::IPC::IPCReply, ::IPC::IPCRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_call_, context, request);
}

::grpc::ClientAsyncResponseReader< ::IPC::IPCReply>* IPCSrv::Stub::AsynccallRaw(::grpc::ClientContext* context, const ::IPC::IPCRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsynccallRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::IPC::IPCReply>* IPCSrv::Stub::streamCallRaw(::grpc::ClientContext* context, const ::IPC::IPCRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::IPC::IPCReply>::Create(channel_.get(), rpcmethod_streamCall_, context, request);
}

void IPCSrv::Stub::async::streamCall(::grpc::ClientContext* context, const ::IPC::IPCRequest* request, ::grpc::ClientReadReactor< ::IPC::IPCReply>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::IPC::IPCReply>::Create(stub_->channel_.get(), stub_->rpcmethod_streamCall_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::IPC::IPCReply>* IPCSrv::Stub::AsyncstreamCallRaw(::grpc::ClientContext* context, const ::IPC::IPCRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::IPC::IPCReply>::Create(channel_.get(), cq, rpcmethod_streamCall_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::IPC::IPCReply>* IPCSrv::Stub::PrepareAsyncstreamCallRaw(::grpc::ClientContext* context, const ::IPC::IPCRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::IPC::IPCReply>::Create(channel_.get(), cq, rpcmethod_streamCall_, context, request, false, nullptr);
}

::grpc::ClientReader< ::IPC::FileReply>* IPCSrv::Stub::recordDownloadRaw(::grpc::ClientContext* context, const ::IPC::IPCRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::IPC::FileReply>::Create(channel_.get(), rpcmethod_recordDownload_, context, request);
}

void IPCSrv::Stub::async::recordDownload(::grpc::ClientContext* context, const ::IPC::IPCRequest* request, ::grpc::ClientReadReactor< ::IPC::FileReply>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::IPC::FileReply>::Create(stub_->channel_.get(), stub_->rpcmethod_recordDownload_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::IPC::FileReply>* IPCSrv::Stub::AsyncrecordDownloadRaw(::grpc::ClientContext* context, const ::IPC::IPCRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::IPC::FileReply>::Create(channel_.get(), cq, rpcmethod_recordDownload_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::IPC::FileReply>* IPCSrv::Stub::PrepareAsyncrecordDownloadRaw(::grpc::ClientContext* context, const ::IPC::IPCRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::IPC::FileReply>::Create(channel_.get(), cq, rpcmethod_recordDownload_, context, request, false, nullptr);
}

IPCSrv::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      IPCSrv_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< IPCSrv::Service, ::IPC::IPCRequest, ::IPC::IPCReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](IPCSrv::Service* service,
             ::grpc::ServerContext* ctx,
             const ::IPC::IPCRequest* req,
             ::IPC::IPCReply* resp) {
               return service->call(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      IPCSrv_method_names[1],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< IPCSrv::Service, ::IPC::IPCRequest, ::IPC::IPCReply>(
          [](IPCSrv::Service* service,
             ::grpc::ServerContext* ctx,
             const ::IPC::IPCRequest* req,
             ::grpc::ServerWriter<::IPC::IPCReply>* writer) {
               return service->streamCall(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      IPCSrv_method_names[2],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< IPCSrv::Service, ::IPC::IPCRequest, ::IPC::FileReply>(
          [](IPCSrv::Service* service,
             ::grpc::ServerContext* ctx,
             const ::IPC::IPCRequest* req,
             ::grpc::ServerWriter<::IPC::FileReply>* writer) {
               return service->recordDownload(ctx, req, writer);
             }, this)));
}

IPCSrv::Service::~Service() {
}

::grpc::Status IPCSrv::Service::call(::grpc::ServerContext* context, const ::IPC::IPCRequest* request, ::IPC::IPCReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status IPCSrv::Service::streamCall(::grpc::ServerContext* context, const ::IPC::IPCRequest* request, ::grpc::ServerWriter< ::IPC::IPCReply>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status IPCSrv::Service::recordDownload(::grpc::ServerContext* context, const ::IPC::IPCRequest* request, ::grpc::ServerWriter< ::IPC::FileReply>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace IPC

