// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: IPC.proto

#include "IPC.pb.h"
#include "IPC.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace IPC {

static const char* IPCSrv_method_names[] = {
  "/IPC.IPCSrv/call",
};

std::unique_ptr< IPCSrv::Stub> IPCSrv::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< IPCSrv::Stub> stub(new IPCSrv::Stub(channel, options));
  return stub;
}

IPCSrv::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_call_(IPCSrv_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status IPCSrv::Stub::call(::grpc::ClientContext* context, const ::IPC::IPCRequest& request, ::IPC::IPCReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::IPC::IPCRequest, ::IPC::IPCReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_call_, context, request, response);
}

void IPCSrv::Stub::async::call(::grpc::ClientContext* context, const ::IPC::IPCRequest* request, ::IPC::IPCReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::IPC::IPCRequest, ::IPC::IPCReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_call_, context, request, response, std::move(f));
}

void IPCSrv::Stub::async::call(::grpc::ClientContext* context, const ::IPC::IPCRequest* request, ::IPC::IPCReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_call_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::IPC::IPCReply>* IPCSrv::Stub::PrepareAsynccallRaw(::grpc::ClientContext* context, const ::IPC::IPCRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::IPC::IPCReply, ::IPC::IPCRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_call_, context, request);
}

::grpc::ClientAsyncResponseReader< ::IPC::IPCReply>* IPCSrv::Stub::AsynccallRaw(::grpc::ClientContext* context, const ::IPC::IPCRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsynccallRaw(context, request, cq);
  result->StartCall();
  return result;
}

IPCSrv::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      IPCSrv_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< IPCSrv::Service, ::IPC::IPCRequest, ::IPC::IPCReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](IPCSrv::Service* service,
             ::grpc::ServerContext* ctx,
             const ::IPC::IPCRequest* req,
             ::IPC::IPCReply* resp) {
               return service->call(ctx, req, resp);
             }, this)));
}

IPCSrv::Service::~Service() {
}

::grpc::Status IPCSrv::Service::call(::grpc::ServerContext* context, const ::IPC::IPCRequest* request, ::IPC::IPCReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace IPC

