config:
    
    # 接口配置
    api:
        # 使用RPC库
        lib: grpc
        ip: localhost
        port: 9000

    rtmp:
        host: 192.168.0.130
        port: 1935
        app: live

    # 录像配置
    record:
        # 录像机可执行程序
        exec: bin/recorder
        # 录像存储根目录(不能为多级目录)
        path: stream_records
        # 录像间隔时间(单位：分钟)
        interval: 1
        # 通信管道
        fifo: bin/fifo
        # 录像日志存储目录
        log_path: logs/record/spdlog.log

    # 日志配置
    log:
        # 使用日志库
        lib: spdlog
        # 0-控制台 1-文件(按天划分) 2-两者都有
        mode: 2
        console:
            level: debug
            pattern:
        file:
            # 生成日志的名称
            name: logs/global/spdlog.log
            level: debug
            pattern:
            # 每日几点几分重新生成日志文件
            rotation_hour: 2
            rotation_minute: 30
            # 是否覆盖文件
            truncate: false
        # 刷新日志缓存的时机
        flush_on: debug
